// Generated by CoffeeScript 1.7.1
(function() {
  var Bear, app, bodyParser, express, mongoose, port, router;

  express = require('express');

  app = express();

  bodyParser = require('body-parser');

  mongoose = require('mongoose');

  Bear = require('./models/bear');

  mongoose.connect('mongodb://node:node@novus.modulusmongo.net:27017/Iganiq8o');

  app.use(bodyParser());

  port = process.env.PORT || 8080;

  router = express.Router();

  router.get('/', function(req, res) {
    return res.json({
      message: 'hooray! welcome to our api!'
    });
  });

  app.use('/api', router);

  app.listen(port);

  console.log('Magic happens on port ' + port);

}).call(this);
