// Generated by CoffeeScript 1.7.1
(function() {
  var BearSchema, Schema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  BearSchema = new Schema({
    name: String
  });

  module.exports = mongoose.model('Bear', BearSchema);

}).call(this);
